server:
  port: 8083

spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.roombridge: DEBUG
